#!/bin/bash
#Clone the Chef repo from github
mkdir /var/chef
chown ubuntu:ubuntu /var/chef
su ubuntu -c 'git clone git://github.com/csw/chef-repo.git /var/chef'
mkdir /etc/chef
cp /var/chef/solo.rb /etc/chef/solo.rb
